### ISSUE TITLE
Specify license

### ISSUE THREAD

**Issue by fabaff** [angr/pypcode#1]
https://github.com/angr/pypcode/blob/76205b446620f3fd05e097af76cbed301f5031ee/setup.py#L34

The license tag says `GPL`. Could you be more specific, e. g., if it's `GPLv1`, `GPLv1+`, etc.?

Thanks

**Comment by mborgerson** [comment]
This is not under GPL, that was a copy-paste error from a prior module. ICENSE.txt file added to clear things up.
