### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by pwn0rz** [angr/pypcode#11]
Hi, this project is awesome and thanks for the work! I have compiled this project on the Apple Silicon successfully by adding this definition in `Ghidra_9.2.3_build`. 

https://github.com/NationalSecurityAgency/ghidra/blob/4e16b3aa3a649b87a54a6e43a5c01360fd255a83/Ghidra/Features/Decompiler/src/decompile/cpp/types.h#L184

```c
#if defined (__APPLE_CC__) && defined (__aarch64__)
#define HOST_ENDIAN 0
typedef unsigned int uintm;
typedef int intm;
typedef unsigned long uint8;
typedef long int8;
typedef unsigned int uint4;
typedef int int4;
typedef unsigned short uint2;
typedef short int2;
typedef unsigned char uint1;
typedef char int1;
typedef uint8 uintp;
#endif
```

So, could you please help sync with the upstream code so that cursed Apple Silicon users can benefit?

**Comment by mborgerson** [comment]
Thanks! Updated to Ghidra 9.2.3 release now.
