### ISSUE TITLE
Throws "terminate called after throwing an instance of 'LowLevelError'" while translating PowerPC

### ISSUE THREAD

**Issue by kye4u2** [angr/pypcode#16]
Language: PowerPC:LE:64:A2ALT

opcode0 = b"\x0c\x00\xfe\x41"
opcode1 = b"\x25\xde\xff\x4b"

result = context.translate(opcode0, 0)
result = context.translate(opcode1, 0)

Error thrown after executing this translations in sequence : "terminate called after throwing an instance of 'LowlevelError'"

This is what you get in ghidra:
        100021d8 0c 00 fe 41     beq        cr7,LAB_100021e4
                                                      $U1470:1 = COPY 0:1
                                                      $U100:4 = INT_SUB 3:4, 2:4
                                                      $U120:1 = INT_RIGHT cr7, $U100
                                                      $U1470:1 = INT_AND $U120, 1:1
                                                      CBRANCH *[ram]0x100021e4:4, $U1470
        100021dc 25 de ff 4b     bl         Elf64_Ehdr_10000000
                                                      r2Save = COPY r2
                                                      LR = COPY 0x100021e0:8
                                                      CALL *[ram]0x10000000:4

**Comment by nabar33** [comment]
Hi, this bug looks like a similar issue I ran into while working with ARM/Thumb stuff. I isolated why it was happening and did a PR for it that you can check out: https://github.com/angr/pypcode/pull/14

I verified the snippet doesn't crash with my patch if you need something working right away.

Cheers!

**Comment by kye4u2** [comment]
@nabar33  Thanks for sharing the patch!!!
