### ISSUE TITLE
Common registers?

### ISSUE THREAD

**Issue by r4dr3fr4d** [angr/pypcode#25]
Is there a way to query a common register offset (eg, program counter, frame/stack pointer, flags/status) without naming the architecture-specific name (RIP, etc)?

**Comment by mborgerson** [comment]
You can parse the language pspec for `programcounter` and `stackpointer`, e.g.:

```python
pc_tag = lang.pspec.find('programcounter')
pc_reg = pc_tag.attrib.get('register', None)
pc_offset = ctx.registers[pc_reg].offset
```
