### ISSUE TITLE
skipping over data?

### ISSUE THREAD

**Issue by wideglide** [angr/pypcode#29]
Would it be possible to skip over data that is mixed with code (ARM) instead of returning?

Looking at incrementing the offset by the default instruction alignment here instead of the `break`:
https://github.com/angr/pypcode/blob/b0b91c3ac57b8bcbc94c3d5825799f6e3b2f6c2f/pypcode/native/csleigh.cc#L336-L340

**Comment by mborgerson** [comment]
pypcode is intended not to make such an analysis, and heuristics like advancing by instruction width etc are not exactly reliable. I recommend dealing with this at a higher level, e.g. lifting blocks at a time
