### ISSUE TITLE
How to specify architecture in the pcode engine?

### ISSUE THREAD

**Issue by tneale-gt** [angr/pypcode#79]
### Question

I have tried the angr examples and I'm finding an error related to architecture mapping, so I would like to know the correct way to specify target architecture when using angr with the pcode engine.

For example, with the 0ctf_trace example (https://github.com/angr/angr-examples/tree/master/examples/0ctf_trace), when I run solve.py I have no error. But when I modify it to use the pcode engine instead of VEX by adding "engine=angr.engines.UberEnginePcode" to the project constructor, I see this error:
```
ERROR    | 2023-08-21 16:46:49,214 | angr.engines.pcode.lifter | Unknown mapping of MIPS32 to pcode languge id
```
The problem seems to be that the Project constructor has load_options that specify arch as 'mipsel'. I can't delete this argument because an architecture is required for the blob backend. But 'mipsel' is apparently not correct for pypcode.

Similarly, I can run the android_arm_license_validation example (https://github.com/angr/angr-examples/tree/master/examples/android_arm_license_validation) using VEX, but when I modify solve.py to use the pcode engine I see this error:
```
ERROR    | 2023-08-21 16:52:25,375 | angr.engines.pcode.lifter | Unknown mapping of ARMEL to pcode languge id
```

In this case there is no arch parameter, and angr has determined the architecture to be ARM:
```
>>> b = angr.Project("./validate", load_options = load_options, auto_load_libs=False)
>>> state = b.factory.blank_state(addr=0x401760)
>>> state.arch
<Arch ARMEL (LE)>
```
Should I be using the arch parameter to set a pcode language ID?

Any assistance much appreciated.

Version info:
Host: Ubuntu20 (Linux 5.4.0-156-generic #173-Ubuntu SMP Tue Jul 11 07:25:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux)
python: 3.8.10
angr, cle, claripy, pyvex, 9.2.64
pypcode: 1.1.2
capstone: 5.0.0.post1
cffi: 1.15.1
pycparser: 2.21

**Comment by Whatang** [comment]
I've used this:

```python
ghidra_lang="TI_MSP430:LE:16:default"
pyp_lang = None
for arch in pypcode.Arch.enumerate():
    for lang in arch.languages:
        if lang.id == ghidra_lang:
            pyp_lang = lang
            break
    if pyp_lang is not None:
        break

pcode_arch = archinfo.ArchPcode(pyp_lang)

proj = angr.Project(path_to_binary, arch=pcode_arch, blahblahblah....)
```

The `ghidra_lang` argument is the string that Ghidra uses to refer to the exact architecture you want to use.

**Comment by mborgerson** [comment]
Apologies for the delay. The solution provided by Whatang works, you can also specify an arch like this: `archinfo.ArchPcode("x86:LE:64:default")`
