### ISSUE TITLE
Licence not explicit

### ISSUE THREAD

**Issue by jeshan** [angr/pypcode#8]
Based on this:

https://github.com/angr/pypcode/blob/462f1dbac52e28ce671f5506b29d131cadb334af/setup.py#L33-L34

I'm assuming this project is Apache2-licensed? Please make it explicit.

**Comment by ltfish** [comment]
We (the angr team) generally prefer BSD.

**Comment by mborgerson** [comment]
LICENSE.txt file added to clear things up.

**Comment by jeshan** [comment]
Thanks, I should have checked that there was already an existing issue for that.
