### ISSUE TITLE
Does anyone have any insight regarding newer version performance changes?

### ISSUE THREAD

**Issue by felicro** [angr/pypcode#97]
### Question

I am currently using v1.1.2 within a project I am working on and am looking to improve the overall execution speed by any means necessary. It seems that due to initial design decisions, updating my code to the newer versions would require a good bit of restructuring. I was wondering if anyone had information, or insight regarding how the v2.0+ versions and the v1.1.2 version compare in terms of performance? More specifically, instruction translation speeds and memory usage? Is there much of a difference?

Thanks in advance for any assistance!

**Comment by ltfish** [comment]
IMO https://github.com/angr/pypcode/commit/8be751a99cd1f915d58ed01ded012243159bb57e is the commit that brings the biggest performance improvement. I did not pay attention to memory usage, but the speed improvement during block lifting is over 10x once we switched to nanobind.

**Comment by felicro** [comment]
Oh, wow. Thanks so much for your response. That is really good! I guess I am doing the update after all. Thanks again.

**Comment by ltfish** [comment]
It was @mborgerson who made all the performance improvement happen!
