### ISSUE TITLE
Cannot translate c-program under sparc to p-code?

### ISSUE THREAD

**Issue by Xmuwgl** [angr/pypcode#98]
### Question

Accroding to the docs, I tried to translate a binary file of the SPARC architecture into pcode, and I ran the following code: 

```Python
ctx = Context("x86:LE:64:default")
tx = ctx.translate(bin_data)
```

However, I encountered the following error: 

> LowlevelError: Could not obtain cached delay slot instruction

I have tried multiple SPARC files, and I get the same error every time.

I want to know if pypcode does not support the translation of SPARC architecture files?

By the way, the files' arch is:
> ELF 64-bit MSB relocatable, SPARC V9, relaxed memory ordering, version 1 (SYSV), not stripped.

**Comment by ltfish** [comment]
You specified `"x86:LE:64:default"`, which is for x86-64. You should use the language ID for SPARC v9 instead.

**Comment by Xmuwgl** [comment]
> You specified `"x86:LE:64:default"`, which is for x86-64. You should use the language ID for SPARC v9 instead.

Sorry, I copied a wrong code here. In fact, the code is `"ctx = Context("sparc:BE:64:default")"`. And the question is the same, `"LowlevelError: Could not obtain cached delay slot instruction"`. I have no idea how to solve it.

**Comment by Xmuwgl** [comment]
For your information, I ran the code in the Colab, free version, and the complete codes like below:
```Python
!pip install pypcode
from pypcode import Context, PcodePrettyPrinter
ctx = Context("sparc:BE:64:default")
with open('example', 'rb') as f:
    bin_data = f.read()
tx = ctx.translate(bin_data)
```
I would be appreciated it if you can locate the error cause.

**Comment by ltfish** [comment]
The error message is from here: https://github.com/NationalSecurityAgency/ghidra/blob/master/Ghidra/Features/Decompiler/src/decompile/cpp/sleigh.cc#L385

Did you provide enough bytes for the block you are trying to lift? It's possible that your `bin_data` does not include the delay slot instruction.

**Comment by ltfish** [comment]
> For your information, I ran the code in the Colab, free version, and the complete codes like below:
> 
> ```python
> !pip install pypcode
> from pypcode import Context, PcodePrettyPrinter
> ctx = Context("sparc:BE:64:default")
> with open('example', 'rb') as f:
>     bin_data = f.read()
> tx = ctx.translate(bin_data)
> ```
> 
> I would be appreciated it if you can locate the error cause.

Oh I see. You are treating the ELF file as a collection of instruction bytes, which ignores the structure of the ELF file itself.

You need something that parses the ELF file for you before you can recognize where the instruction bytes are. You will then only pass the bytes of a basic block to `ctx.translate()`.

You can give Ghidra or angr management a try.

**Comment by Xmuwgl** [comment]
> > For your information, I ran the code in the Colab, free version, and the complete codes like below:
> > ```python
> > !pip install pypcode
> > from pypcode import Context, PcodePrettyPrinter
> > ctx = Context("sparc:BE:64:default")
> > with open('example', 'rb') as f:
> >     bin_data = f.read()
> > tx = ctx.translate(bin_data)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I would be appreciated it if you can locate the error cause.
> 
> Oh I see. You are treating the ELF file as a collection of instruction bytes, which ignores the structure of the ELF file itself.
> 
> You need something that parses the ELF file for you before you can recognize where the instruction bytes are. You will then only pass the bytes of a basic block to `ctx.translate()`.
> 
> You can give Ghidra or angr management a try.

Thanks a lot! I run the following code and get the correct output.
```Python
ctx = Context("sparc:BE:32:default")
tx = ctx.translate(b"\x80\xA6\x20\x63\x14\x80\x00\x23\x01\x00\x00\x00")
for op in tx.ops:
    print(PcodePrettyPrinter.fmt_op(op))
````
